#!/bin/bash
#set -xv
#
# Usage:	xtt { title }	# default is username@hostname
#
if [ "$1" != "" ]
then
	title="$1"
else
	if [ "$USER" = "fxo" ]
	then
		title=`uname -n`
	else
		title="`whoami`@`uname -n`"
	fi
fi

echo -n "]0;$title"
